'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';

export default function Footer() {
  const pathname = usePathname();
  const locale = pathname.startsWith('/en') ? 'en'
    : pathname.startsWith('/pl') ? 'pl'
    : pathname.startsWith('/de') ? 'de'
    : 'uk';

  const links = {
    uk: {
      disclaimer: 'Дисклеймер',
      privacy: 'Політика конфіденційності',
      terms: 'Умови використання',
      affiliate: 'Партнерські посилання',
      notAdvice: '⚠️ Не є фінансовою порадою. Тільки для освітніх цілей.',
      extended: 'Весь контент на сайті, включно з аналізом, прогнозами та рекомендаціями "купити/продати/тримати", згенеровано штучним інтелектом і має виключно інформаційний та освітній характер. Це не інвестиційна, фінансова, юридична чи податкова порада. Криптовалютні ринки надзвичайно волатильні — ви можете втратити частину або всі вкладені кошти. Минулі результати не гарантують майбутніх. Перш ніж приймати будь-які фінансові рішення, проконсультуйтеся з кваліфікованим фінансовим радником.',
      rights: '© 2026 CryptoNavigator. Всі права захищені.',
    },
    en: {
      disclaimer: 'Disclaimer',
      privacy: 'Privacy Policy',
      terms: 'Terms of Use',
      affiliate: 'Affiliate Disclosure',
      notAdvice: '⚠️ Not financial advice. For educational purposes only.',
      extended: 'All content on this site, including analysis, forecasts, and "buy/sell/hold" recommendations, is generated by artificial intelligence and is for informational and educational purposes only. It is not investment, financial, legal, or tax advice. Cryptocurrency markets are highly volatile — you may lose some or all of your invested funds. Past performance does not guarantee future results. Consult a qualified financial advisor before making any financial decisions.',
      rights: '© 2026 CryptoNavigator. All rights reserved.',
    },
    pl: {
      disclaimer: 'Zastrzeżenia',
      privacy: 'Polityka prywatności',
      terms: 'Warunki użytkowania',
      affiliate: 'Ujawnienie afiliacji',
      notAdvice: '⚠️ Nie jest poradą finansową. Tylko do celów edukacyjnych.',
      extended: 'Cała zawartość tej strony, w tym analizy, prognozy i rekomendacje „kup/sprzedaj/trzymaj”, jest generowana przez sztuczną inteligencję i ma charakter wyłącznie informacyjny i edukacyjny. Nie stanowi to porady inwestycyjnej, finansowej, prawnej ani podatkowej. Rynki kryptowalut są wyjątkowo zmienne — możesz stracić część lub całość zainwestowanych środków. Wyniki osiągnięte w przeszłości nie gwarantują przyszłych rezultatów. Przed podjęciem jakichkolwiek decyzji finansowych skonsultuj się z wykwalifikowanym doradcą finansowym.',
      rights: '© 2026 CryptoNavigator. Wszelkie prawa zastrzeżone.',
    },
    de: {
      disclaimer: 'Haftungsausschluss',
      privacy: 'Datenschutzrichtlinie',
      terms: 'Nutzungsbedingungen',
      affiliate: 'Affiliate-Offenlegung',
      notAdvice: '⚠️ Keine Finanzberatung. Nur zu Bildungszwecken.',
      extended: 'Alle Inhalte auf dieser Website, einschließlich Analysen, Prognosen und „Kaufen/Verkaufen/Halten“-Empfehlungen, werden von künstlicher Intelligenz generiert und dienen ausschließlich Informations- und Bildungszwecken. Es handelt sich nicht um eine Anlage-, Finanz-, Rechts- oder Steuerberatung. Kryptowährungsmärkte sind äußerst volatil — Sie können einen Teil oder das gesamte investierte Kapital verlieren. Vergangene Wertentwicklungen sind keine Garantie für zukünftige Ergebnisse. Konsultieren Sie vor finanziellen Entscheidungen einen qualifizierten Finanzberater.',
      rights: '© 2026 CryptoNavigator. Alle Rechte vorbehalten.',
    },
  };

  const t = links[locale as keyof typeof links] || links.uk;

  return (
    <footer className="bg-gray-900 text-gray-300 mt-16">
      {/* Disclaimer banner */}
      <div className="bg-yellow-900/40 border-t border-yellow-700/30 px-4 py-4">
        <div className="max-w-3xl mx-auto">
          <p className="text-center text-yellow-200 text-sm font-medium mb-2">
            {t.notAdvice}
          </p>
          <p className="text-center text-yellow-300/70 text-xs leading-relaxed">
            {t.extended}
          </p>
          {locale === 'uk' && (
            <p className="text-center text-yellow-300/50 text-xs italic mt-2">
              Обпікся на молоці — дутимеш і на воду 🔥💧 Зважайте на ризики.
            </p>
          )}
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-4 py-8">
        <div className="flex flex-col md:flex-row justify-between items-center gap-4">
          {/* Logo */}
          <div>
            <span className="text-white font-black text-lg">CryptoNavigator</span>
            <p className="text-sm text-gray-300 mt-1">cryptotop.chat</p>
          </div>

          {/* Legal links — без мовного префіксу, ці сторінки існують лише в одній версії */}
          <nav className="flex flex-wrap gap-4 text-sm justify-center text-gray-300">
            <Link href="/disclaimer" className="hover:text-orange-400 transition">
              {t.disclaimer}
            </Link>
            <Link href="/privacy" className="hover:text-orange-400 transition">
              {t.privacy}
            </Link>
            <Link href="/terms" className="hover:text-orange-400 transition">
              {t.terms}
            </Link>
            <Link href="/disclaimer#affiliate" className="hover:text-orange-400 transition">
              {t.affiliate}
            </Link>
          </nav>
        </div>

        {/* Product Hunt Badge */}
        <div className="flex justify-center mt-6">
          <a
            href="https://www.producthunt.com/posts/cryptonavigator"
            target="_blank"
            rel="noopener noreferrer"
          >
            <img
              src="https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=cryptonavigator&theme=dark"
              alt="CryptoNavigator - Featured on Product Hunt"
              width="250"
              height="54"
            />
          </a>
        </div>

        {/* Bottom line */}
        <div className="border-t border-gray-800 mt-6 pt-4 text-center text-sm text-gray-400">
          <p>{t.rights}</p>
        </div>
      </div>
    </footer>
  );
}
