'use client';
import Link from 'next/link';
import { usePathname, useSearchParams } from 'next/navigation';
import { Suspense } from 'react';

function FooterInner() {
  const pathname = usePathname();
  const searchParams = useSearchParams();
  const langParam = searchParams.get('lang');
  const isArticlePage = /^\/blog\/[^/]+$/.test(pathname);

  const locale = isArticlePage && (langParam === 'en' || langParam === 'pl' || langParam === 'de')
    ? langParam
    : pathname.startsWith('/en') ? 'en'
    : pathname.startsWith('/pl') ? 'pl'
    : pathname.startsWith('/de') ? 'de'
    : 'uk';

  const links = {
    uk: {
      disclaimer: 'Дисклеймер',
      privacy: 'Політика конфіденційності',
      terms: 'Умови використання',
      affiliate: 'Партнерські посилання',
      notAdvice: '⚠️ Не є фінансовою порадою. Тільки для освітніх цілей.',
      extended: 'Весь контент на сайті, включно з аналізом, прогнозами та рекомендаціями "купити/продати/тримати", згенеровано штучним інтелектом і має виключно інформаційний та освітній характер. Це не інвестиційна, фінансова, юридична чи податкова порада. Криптовалютні ринки надзвичайно волатильні — ви можете втратити частину або всі вкладені кошти. Минулі результати не гарантують майбутніх. Перш ніж приймати будь-які фінансові рішення, проконсультуйтеся з кваліфікованим фінансовим радником.',
      rights: '© 2026 CryptoNavigator. Всі права захищені.',
      legalBase: '',
    },
    en: {
      disclaimer: 'Disclaimer',
      privacy: 'Privacy Policy',
      terms: 'Terms of Use',
      affiliate: 'Affiliate Disclosure',
      notAdvice: '⚠️ Not financial advice. For educational purposes only.',
      extended: 'All content on this site, including analysis, forecasts, and "buy/sell/hold" recommendations, is generated by artificial intelligence and is for informational and educational purposes only. It is not investment, financial, legal, or tax advice. Cryptocurrency markets are highly volatile — you may lose some or all of your invested funds. Past performance does not guarantee future results. Consult a qualified financial advisor before making any financial decisions.',
      rights: '© 2026 CryptoNavigator. All rights reserved.',
      legalBase: '/en',
    },
    pl: {
      disclaimer: 'Zastrzeżenia',
      privacy: 'Polityka prywatności',
      terms: 'Warunki użytkowania',
      affiliate: 'Ujawnienie afiliacji',
      notAdvice: '⚠️ Nie jest poradą finansową. Tylko do celów edukacyjnych.',
      extended: 'Cała zawartość tej strony, w tym analizy, prognozy i rekomendacje „kup/sprzedaj/trzymaj", jest generowana przez sztuczną inteligencję i ma charakter wyłącznie informacyjny i edukacyjny. Nie stanowi to porady inwestycyjnej, finansowej, prawnej ani podatkowej. Rynki kryptowalut są wyjątkowo zmienne — możesz stracić część lub całość zainwestowanych środków. Wyniki osiągnięte w przeszłości nie gwarantują przyszłych rezultatów. Przed podjęciem jakichkolwiek decyzji finansowych skonsultuj się z wykwalifikowanym doradcą finansowym.',
      rights: '© 2026 CryptoNavigator. Wszelkie prawa zastrzeżone.',
      legalBase: '/pl',
    },
    de: {
      disclaimer: 'Haftungsausschluss',
      privacy: 'Datenschutzrichtlinie',
      terms: 'Nutzungsbedingungen',
      affiliate: 'Affiliate-Offenlegung',
      notAdvice: '⚠️ Keine Finanzberatung. Nur zu Bildungszwecken.',
      extended: 'Alle Inhalte auf dieser Website, einschließlich Analysen, Prognosen und „Kaufen/Verkaufen/Halten"-Empfehlungen, werden von künstlicher Intelligenz generiert und dienen ausschließlich Informations- und Bildungszwecken. Es handelt sich nicht um eine Anlage-, Finanz-, Rechts- oder Steuerberatung. Kryptowährungsmärkte sind äußerst volatil — Sie können einen Teil oder das gesamte investierte Kapital verlieren. Vergangene Wertentwicklungen sind keine Garantie für zukünftige Ergebnisse. Konsultieren Sie vor finanziellen Entscheidungen einen qualifizierten Finanzberater.',
      rights: '© 2026 CryptoNavigator. Alle Rechte vorbehalten.',
      legalBase: '/de',
    },
  };

  const t = links[locale as keyof typeof links] || links.uk;

  return (
    <footer style={{ backgroundColor: '#FDF6EC', borderTop: '1px solid #E8D5B7' }} className="mt-16">

      {/* Disclaimer banner */}
      <div style={{ backgroundColor: '#FEF3DC', borderBottom: '1px solid #E8D5B7' }} className="px-4 py-6">
        <div className="max-w-3xl mx-auto">
          <p className="text-center text-base font-black mb-3" style={{ color: '#7C2D12' }}>
            {t.notAdvice}
          </p>
          <p className="text-center text-sm leading-relaxed" style={{ color: '#92400E' }}>
            {t.extended}
          </p>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-4 py-8">
        <div className="flex flex-col md:flex-row justify-between items-center gap-6">

          {/* Logo */}
          <div>
            <span className="font-black text-xl" style={{ color: '#111827' }}>CryptoNavigator</span>
            <p className="text-base font-semibold mt-1" style={{ color: '#374151' }}>cryptotop.chat</p>
          </div>

          {/* Legal links */}
          <nav className="flex flex-wrap gap-5 text-sm font-semibold justify-center">
            <Link href={`${t.legalBase}/disclaimer`} className="transition hover:text-orange-500" style={{ color: '#1F2937' }}>
              {t.disclaimer}
            </Link>
            <Link href={`${t.legalBase}/privacy`} className="transition hover:text-orange-500" style={{ color: '#1F2937' }}>
              {t.privacy}
            </Link>
            <Link href={`${t.legalBase}/terms`} className="transition hover:text-orange-500" style={{ color: '#1F2937' }}>
              {t.terms}
            </Link>
            <Link href={`${t.legalBase}/disclaimer#affiliate`} className="transition hover:text-orange-500" style={{ color: '#1F2937' }}>
              {t.affiliate}
            </Link>
          </nav>
        </div>

        {/* Product Hunt Badge */}
        <div className="flex justify-center mt-6">
          <a href="https://www.producthunt.com/posts/cryptonavigator" target="_blank" rel="noopener noreferrer">
            <img
              src="https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=cryptonavigator&theme=light"
              alt="CryptoNavigator - Featured on Product Hunt"
              width="250" height="54"
            />
          </a>
        </div>

        {/* Bottom line */}
        <div className="mt-6 pt-4 text-center text-sm font-semibold" style={{ borderTop: '1px solid #E8D5B7', color: '#374151' }}>
          <p>{t.rights}</p>
        </div>
      </div>
    </footer>
  );
}

export default function Footer() {
  return (
    <Suspense fallback={null}>
      <FooterInner />
    </Suspense>
  );
}
