import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Use — CryptoNavigator',
  description: 'Terms of Use for CryptoNavigator (cryptotop.chat)',
  alternates: { canonical: 'https://cryptotop.chat/en/terms' },
};

export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-4 py-12 text-gray-800">
      <h1 className="text-3xl font-black mb-2">Terms of Use</h1>
      <p className="text-sm text-gray-400 mb-8">Last updated: June 2026</p>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">1. Acceptance of terms</h2>
        <p>By using CryptoNavigator at <a href="https://cryptotop.chat" className="text-orange-500 hover:underline">cryptotop.chat</a>, you agree to these Terms of Use. If you do not agree, please do not use our website.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">2. Educational purpose only</h2>
        <p className="mb-2">CryptoNavigator is an <strong>educational platform</strong>. All content, including news analysis, market data, recommendations (buy/sell/hold), and simulator features, is provided for <strong>informational and educational purposes only</strong>.</p>
        <div className="bg-orange-50 border border-orange-200 rounded-xl p-4 mt-3">
          <p className="font-bold text-orange-800">⚠️ IMPORTANT DISCLAIMER</p>
          <p className="text-orange-700 mt-1">Nothing on this site constitutes financial, investment, legal or tax advice. Do not rely solely on information from this website when making financial decisions. Always consult a qualified financial advisor before investing.</p>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">3. Trading simulator</h2>
        <p>The CryptoNavigator trading simulator uses only virtual (non-real) funds. It is designed for educational purposes — to help users understand cryptocurrency trading principles without financial risk. Any gains or losses in the simulator do not reflect real financial results.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">4. Affiliate relationships</h2>
        <p>CryptoNavigator participates in affiliate programs with cryptocurrency exchanges, including Binance, Bybit, OKX and KuCoin. We may earn a commission when you register or trade through our affiliate links. This does not affect the price you pay. Our editorial content is independent of affiliate relationships.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">5. AI-generated content</h2>
        <p>News analysis and summaries on this platform are generated by artificial intelligence (Anthropic Claude). While we strive for accuracy, AI content may contain errors or inaccuracies. Always verify important information from primary sources before making decisions.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">6. Intellectual property</h2>
        <p>All original content, design, and code on CryptoNavigator are our intellectual property. News summaries are AI-generated analyses based on publicly available information with references to primary sources. If you believe any content infringes your copyright, contact us at info@cryptotop.chat.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">7. Limitation of liability</h2>
        <p>CryptoNavigator is not liable for any financial losses, damages or negative consequences resulting from the use of our platform or reliance on our content. Cryptocurrency trading carries substantial risk of loss. You use the platform at your own risk.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">8. Third-party links</h2>
        <p>Our website contains links to third-party resources, including cryptocurrency exchanges. We are not responsible for the content, security or practices of those external sites. Visit them at your own risk.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">9. Prohibited use</h2>
        <p className="mb-2">You agree not to:</p>
        <ul className="list-disc pl-6 space-y-1">
          <li>Use the platform for illegal purposes</li>
          <li>Attempt to reverse engineer or copy our software</li>
          <li>Use automated scrapers or bots to collect content</li>
          <li>Misrepresent or use our content in a misleading way</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">10. Changes to terms</h2>
        <p>We reserve the right to modify these Terms at any time. Continued use of the platform after changes constitutes acceptance of the new Terms.</p>
      </section>

      <section>
        <h2 className="text-xl font-bold mb-3">11. Contact</h2>
        <p>Questions about these Terms: <strong>info@cryptotop.chat</strong></p>
      </section>
    </main>
  );
}
