import { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';

interface Article {
  id: number;
  title: string;
  title_uk: string;
  coin_slug: string;
  coin_name: string;
  sentiment: string;
  recommendation: string;
  source_url: string;
  source_name: string;
  published_at: string;
  summary: string;
  summary_en: string;
  summary_pl: string;
  summary_de: string;
  full_article_uk: string;
  full_article_en: string;
  meta_description_uk: string;
  meta_description_en: string;
  tags: string[];
}

type Locale = 'uk' | 'en' | 'pl' | 'de';

const UI: Record<Locale, {
  back: string;
  aiNotice: string;
  readOriginal: string;
  sentiment: Record<string, string>;
  rec: Record<string, string>;
  ctaTitle: string;
  ctaText: string;
  ctaButton: string;
  source: string;
}> = {
  uk: {
    back: '← Назад до блогу',
    aiNotice: 'Аналіз згенеровано штучним інтелектом і не є фінансовою порадою. Рекомендації носять виключно інформаційний характер.',
    readOriginal: 'Читати оригінал на',
    sentiment: { positive: '📈 Позитив', negative: '📉 Негатив', neutral: '⚖️ Нейтрально' },
    rec: { buy: '📈 Купити', sell: '📉 Продати', hold: '⏸ Тримати' },
    ctaTitle: '🎮 Хочеш перевірити стратегію?',
    ctaText: 'Спробуй безкоштовний симулятор торгівлі — без ризику для реальних грошей.',
    ctaButton: 'Відкрити симулятор →',
    source: 'джерелі',
  },
  en: {
    back: '← Back to blog',
    aiNotice: 'This analysis was generated by AI and is not financial advice. Recommendations are for informational purposes only.',
    readOriginal: 'Read original on',
    sentiment: { positive: '📈 Positive', negative: '📉 Negative', neutral: '⚖️ Neutral' },
    rec: { buy: '📈 Buy', sell: '📉 Sell', hold: '⏸ Hold' },
    ctaTitle: '🎮 Want to test your strategy?',
    ctaText: 'Try our free trading simulator — no risk to real money.',
    ctaButton: 'Open simulator →',
    source: 'source',
  },
  pl: {
    back: '← Powrót do bloga',
    aiNotice: 'Ta analiza została wygenerowana przez AI i nie stanowi porady finansowej. Rekomendacje mają charakter wyłącznie informacyjny.',
    readOriginal: 'Czytaj oryginał na',
    sentiment: { positive: '📈 Pozytywny', negative: '📉 Negatywny', neutral: '⚖️ Neutralny' },
    rec: { buy: '📈 Kupuj', sell: '📉 Sprzedaj', hold: '⏸ Trzymaj' },
    ctaTitle: '🎮 Chcesz przetestować strategię?',
    ctaText: 'Wypróbuj darmowy symulator tradingowy — bez ryzyka prawdziwych pieniędzy.',
    ctaButton: 'Otwórz symulator →',
    source: 'źródle',
  },
  de: {
    back: '← Zurück zum Blog',
    aiNotice: 'Diese Analyse wurde von KI erstellt und stellt keine Finanzberatung dar. Empfehlungen dienen nur Informationszwecken.',
    readOriginal: 'Original lesen auf',
    sentiment: { positive: '📈 Positiv', negative: '📉 Negativ', neutral: '⚖️ Neutral' },
    rec: { buy: '📈 Kaufen', sell: '📉 Verkaufen', hold: '⏸ Halten' },
    ctaTitle: '🎮 Möchtest du deine Strategie testen?',
    ctaText: 'Probiere unseren kostenlosen Trading-Simulator — ohne Risiko für echtes Geld.',
    ctaButton: 'Simulator öffnen →',
    source: 'Quelle',
  },
};

function parseLocale(value: string | string[] | undefined): Locale {
  const v = Array.isArray(value) ? value[0] : value;
  if (v === 'en' || v === 'pl' || v === 'de') return v;
  return 'uk';
}

async function getArticle(id: string): Promise<Article | null> {
  try {
    const res = await fetch(`https://cryptotop.chat/api/blog/${id}`, { next: { revalidate: 3600 } });
    if (!res.ok) return null;
    const data = await res.json();
    return data.article || null;
  } catch { return null; }
}

// Обирає тіло статті відповідно до локалі: повна стаття (uk/en) > переклад-резюме (pl/de) > summary
function getLocalizedBody(article: Article, locale: Locale): { isFull: boolean; text: string } {
  if (locale === 'uk' && article.full_article_uk && article.full_article_uk.length > 50) {
    return { isFull: true, text: article.full_article_uk };
  }
  if (locale === 'en' && article.full_article_en && article.full_article_en.length > 50) {
    return { isFull: true, text: article.full_article_en };
  }
  if (locale === 'pl' && article.summary_pl) {
    return { isFull: false, text: article.summary_pl };
  }
  if (locale === 'de' && article.summary_de) {
    return { isFull: false, text: article.summary_de };
  }
  if (locale === 'en' && article.summary_en) {
    return { isFull: false, text: article.summary_en };
  }
  return { isFull: false, text: article.summary };
}

function getLocalizedTitle(article: Article, locale: Locale): string {
  if (locale === 'uk') return article.title_uk || article.title;
  return article.title;
}

export async function generateMetadata({
  params,
  searchParams,
}: {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}): Promise<Metadata> {
  const { id } = await params;
  const sp = await searchParams;
  const locale = parseLocale(sp.lang);
  const article = await getArticle(id);
  if (!article) return { title: 'Article not found' };
  const title = getLocalizedTitle(article, locale);
  const description = locale === 'uk'
    ? (article.meta_description_uk || article.summary?.slice(0, 160) || '')
    : (article.meta_description_en || article.summary_en?.slice(0, 160) || '');
  return {
    title: `${title} | CryptoNavigator`,
    description,
    alternates: { canonical: `https://cryptotop.chat/blog/${id}` },
    openGraph: {
      title,
      description,
      type: 'article',
      url: `https://cryptotop.chat/blog/${id}`,
    },
  };
}

const SENTIMENT_COLORS: Record<string, string> = {
  positive: 'bg-green-100 text-green-700',
  negative: 'bg-red-100 text-red-700',
  neutral: 'bg-gray-100 text-gray-700',
};

const RECOMMENDATION_COLORS: Record<string, string> = {
  buy: 'bg-green-500 text-white',
  sell: 'bg-red-500 text-white',
  hold: 'bg-yellow-400 text-gray-900',
};

export default async function ArticlePage({
  params,
  searchParams,
}: {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}) {
  const { id } = await params;
  const sp = await searchParams;
  const locale = parseLocale(sp.lang);
  const t = UI[locale];

  const article = await getArticle(id);
  if (!article) notFound();

  const dateLocaleMap: Record<Locale, string> = { uk: 'uk-UA', en: 'en-US', pl: 'pl-PL', de: 'de-DE' };
  const date = new Date(article.published_at).toLocaleDateString(dateLocaleMap[locale], {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  const sentiment = article.sentiment?.toLowerCase() || 'neutral';
  const rec = article.recommendation?.toLowerCase() || 'hold';
  const displayTitle = getLocalizedTitle(article, locale);
  const body = getLocalizedBody(article, locale);

  const backHref = locale === 'uk' ? '/blog' : `/blog?lang=${locale}`;

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "NewsArticle",
    "headline": displayTitle,
    "description": article.meta_description_uk || article.summary?.slice(0, 160) || "",
    "datePublished": article.published_at,
    "dateModified": article.published_at,
    "author": {
      "@type": "Organization",
      "name": "CryptoNavigator",
      "url": "https://cryptotop.chat"
    },
    "publisher": {
      "@type": "Organization",
      "name": "CryptoNavigator",
      "logo": { "@type": "ImageObject", "url": "https://cryptotop.chat/favicon.ico" }
    },
    "mainEntityOfPage": { "@type": "WebPage", "@id": `https://cryptotop.chat/blog/${article.id}` },
    "keywords": [article.coin_name, "криптовалюта", "крипто новини", ...(article.tags || [])].filter(Boolean).join(", "),
    "inLanguage": locale,
    "isAccessibleForFree": true,
  };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <div className="max-w-3xl mx-auto px-4 py-10">

        {/* Навігація */}
        <Link href={backHref} className="text-orange-600 hover:underline text-sm font-semibold mb-6 inline-block">
          {t.back}
        </Link>

        {/* Бейджі */}
        <div className="flex items-center gap-2 mb-4 flex-wrap">
          {article.coin_name && (
            <span className="bg-orange-100 text-orange-700 text-xs font-bold px-3 py-1 rounded-full uppercase">
              {article.coin_name}
            </span>
          )}
          <span className={`text-xs font-bold px-3 py-1 rounded-full capitalize ${SENTIMENT_COLORS[sentiment] || SENTIMENT_COLORS.neutral}`}>
            {t.sentiment[sentiment] || t.sentiment.neutral}
          </span>
          <span className={`text-xs font-bold px-3 py-1 rounded-full ${RECOMMENDATION_COLORS[rec] || RECOMMENDATION_COLORS.hold}`}>
            {t.rec[rec] || t.rec.hold}
          </span>
          <span className="text-sm text-gray-500 ml-auto">{date}</span>
        </div>

        {/* Заголовок */}
        <h1 className="text-2xl md:text-3xl font-black text-gray-900 mb-6 leading-tight">
          {displayTitle}
        </h1>

        {/* Disclaimer */}
        <div className="bg-yellow-50 border border-yellow-200 rounded-xl px-4 py-3 flex items-start gap-2 mb-6">
          <span className="text-yellow-600 font-bold text-sm mt-0.5">⚠️</span>
          <p className="text-yellow-800 text-sm leading-relaxed">
            {t.aiNotice}
          </p>
        </div>

        {/* Тіло статті: повний текст або переклад-резюме залежно від мови */}
        <div className="bg-white border border-gray-100 rounded-2xl p-6 shadow-sm mb-6">
          {body.isFull ? (
            <div className="prose prose-gray max-w-none">
              {body.text.split('\n').filter(p => p.trim()).map((paragraph, i) => (
                <p key={i} className="text-gray-800 text-base leading-relaxed mb-4">
                  {paragraph}
                </p>
              ))}
            </div>
          ) : (
            <p className="text-gray-800 text-base leading-relaxed font-medium">
              {body.text}
            </p>
          )}
        </div>

        {/* Теги */}
        {article.tags && article.tags.length > 0 && (
          <div className="flex flex-wrap gap-2 mb-6">
            {article.tags.map((tag, i) => (
              <span key={i} className="text-xs bg-gray-100 text-gray-700 px-3 py-1 rounded-full">
                #{tag}
              </span>
            ))}
          </div>
        )}

        {/* CTA симулятор */}
        <div className="bg-orange-50 border border-orange-200 rounded-2xl p-6 mb-6">
          <p className="font-bold text-orange-800 mb-2">{t.ctaTitle}</p>
          <p className="text-orange-700 text-sm mb-4">{t.ctaText}</p>
          <Link href={locale === 'uk' ? '/simulator' : `/${locale}/simulator`} className="inline-block bg-orange-500 hover:bg-orange-600 text-white font-bold px-6 py-2 rounded-xl text-sm transition">
            {t.ctaButton}
          </Link>
        </div>

        {/* Посилання на оригінал */}
        {article.source_url && (
          <a href={article.source_url} target="_blank" rel="noopener noreferrer"
            className="inline-flex items-center gap-2 bg-gray-900 hover:bg-gray-700 text-white font-bold px-6 py-3 rounded-xl transition text-sm">
            {t.readOriginal} {article.source_name || t.source} →
          </a>
        )}

      </div>
    </>
  );
}
