import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Disclaimer — CryptoNavigator',
  description: 'Legal disclaimer and risk notice for CryptoNavigator (cryptotop.chat)',
  alternates: { canonical: 'https://cryptotop.chat/en/disclaimer' },
};

export default function DisclaimerPage() {
  return (
    <main className="max-w-3xl mx-auto px-4 py-12 text-gray-800">
      <h1 className="text-3xl font-black mb-2">Disclaimer</h1>
      <p className="text-sm text-gray-400 mb-8">Last updated: June 2026</p>

      <div className="bg-red-50 border-l-4 border-red-500 rounded-xl p-6 mb-10">
        <p className="font-black text-red-800 text-lg mb-2">⚠️ NOT FINANCIAL ADVICE</p>
        <p className="text-red-700">All content on CryptoNavigator is provided for <strong>educational and informational purposes only</strong>. Nothing on this site constitutes financial, investment, trading, legal or tax advice.</p>
      </div>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">Investment risks</h2>
        <p>Cryptocurrency markets are highly volatile. Prices may rise or fall sharply in a short period. You may lose part or all of your invested funds. Past performance is not indicative of future results.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">AI-generated analysis</h2>
        <p>News summaries, market sentiment analysis and buy/sell/hold signals shown on the platform are generated by artificial intelligence. These are <strong>automated algorithmic assessments</strong>, not professional financial advice. They may be inaccurate, incomplete or outdated.</p>
      </section>

      <section className="mb-8" id="affiliate">
        <h2 className="text-xl font-bold mb-3">Affiliate links</h2>
        <p>CryptoNavigator includes affiliate links to cryptocurrency exchanges. We may earn a commission if you register or trade through our links. This is how we fund the platform. Our analysis and recommendations are <strong>not influenced</strong> by affiliate partnerships.</p>
        <p className="mt-2">Affiliate exchanges: Binance, Bybit, OKX, KuCoin.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">No warranty of accuracy</h2>
        <p>While we strive to provide accurate and up-to-date information, we make no guarantees regarding the completeness, accuracy, reliability, or availability of any information on the platform.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">Your responsibility</h2>
        <p>Any financial decisions you make are your own responsibility. We strongly recommend consulting a qualified financial advisor before making any investment decisions.</p>
      </section>

      <section>
        <h2 className="text-xl font-bold mb-3">Contact</h2>
        <p>Questions about this disclaimer: <strong>info@cryptotop.chat</strong></p>
      </section>
    </main>
  );
}
