import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Disclaimer — CryptoNavigator',
  description: 'Financial disclaimer for CryptoNavigator (cryptotop.chat)',
  alternates: { canonical: 'https://cryptotop.chat/disclaimer' },
};

export default function DisclaimerPage() {
  return (
    <main className="max-w-3xl mx-auto px-4 py-12 text-gray-800">
      <h1 className="text-3xl font-black mb-2">Disclaimer</h1>
      <p className="text-sm text-gray-400 mb-8">Last updated: June 2026</p>

      <div className="bg-red-50 border-l-4 border-red-500 rounded-xl p-6 mb-10">
        <p className="font-black text-red-800 text-lg mb-2">⚠️ NOT FINANCIAL ADVICE</p>
        <p className="text-red-700">All content on CryptoNavigator is for <strong>educational and informational purposes only</strong>. Nothing on this website should be construed as financial, investment, trading, legal, or tax advice.</p>
      </div>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">Investment Risk</h2>
        <p>Cryptocurrency markets are highly volatile. The value of cryptocurrencies can increase or decrease dramatically in a short period of time. You may lose some or all of your investment. Past performance is not indicative of future results.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">AI-Generated Analysis</h2>
        <p>News summaries, sentiment analysis, and buy/sell/hold recommendations displayed on this platform are generated by artificial intelligence. These are <strong>automated algorithmic assessments</strong>, not professional financial advice. They may be inaccurate, incomplete, or outdated.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">Affiliate Disclosure</h2>
        <p>CryptoNavigator contains affiliate links to cryptocurrency exchanges. We earn a commission if you register or trade using our links. This is how we fund the platform. Our analysis and recommendations are <strong>not influenced</strong> by affiliate relationships.</p>
        <p className="mt-2">Affiliated exchanges: Binance, Bybit, OKX, KuCoin.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">No Guarantee of Accuracy</h2>
        <p>While we strive to provide accurate and up-to-date information, we make no representations or warranties about the completeness, accuracy, reliability, or availability of any information on the platform.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3">Your Responsibility</h2>
        <p>Any financial decisions you make are entirely your own responsibility. We strongly recommend consulting with a qualified financial advisor before making any investment decisions.</p>
      </section>

      <section>
        <h2 className="text-xl font-bold mb-3">Contact</h2>
        <p>Questions about this disclaimer: <strong>info@cryptotop.chat</strong></p>
      </section>
    </main>
  );
}
